[project]
name = "hospital-management-system"
version = "0.1.0"
description = "A Hospital Management System web application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask",
    "flask-sqlalchemy",
    "flask-security-too",
    "flask-caching",
    "bcrypt",
    "werkzeug",
    "email_validator",
    "celery",
    "redis",
    "pandas",
    "bleach>=6.3.0",
    "argon2-cffi>=25.1.0"
]

[project.optional-dependencies]
dev = ["pytest"]


