[project]
name = "hospital-management-system"
version = "0.1.0"
description = "A Hospital Management System web application"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "flask",
    "flask-sqlalchemy",
    "flask-security-too",
    "bcrypt",
    "werkzeug",
    "email_validator"
]

[project.optional-dependencies]
dev = ["pytest"]


