"""Celery eager-mode task execution tests."""

import os

import pytest

from models.database import ExportJob, Patient, User, db


@pytest.fixture()
def celery_app(test_client):
    from backend.celery_config import celery

    celery.conf.update(task_always_eager=True, task_eager_propagates=True)
    return celery


@pytest.fixture()
def patient_user(test_client):
    with test_client.application.app_context():
        user = User.query.filter_by(username="patient").first()
        assert user is not None
        yield user


def test_export_task_creates_file(celery_app, test_client, patient_user):
    from backend.tasks import export_patient_treatments

    with test_client.application.app_context():
        patient = Patient.query.filter_by(user_id=patient_user.id).first()
        assert patient is not None

        job = ExportJob(patient_id=patient.id, status="pending")
        db.session.add(job)
        db.session.commit()

        result = export_patient_treatments.delay(patient.id, job.id)
        assert result.successful()

        payload = result.result
        assert payload["success"] is True
        assert os.path.exists(payload["file_path"])

        # Cleanup export file generated by the task.
        if os.path.exists(payload["file_path"]):
            os.remove(payload["file_path"])
